# render.yaml
services:
  - type: web
    name: agentic-travel-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GOOGLE_API_KEY
        value: ${GOOGLE_API_KEY}
      - key: SERPER_API_KEY
        value: ${SERPER_API_KEY}
      - key: FIRECRAWL_API_KEY
        value: ${FIRECRAWL_API_KEY}
      - key: GROQ_API_KEY
        value: ${GROQ_API_KEY}

  


